version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ec_key.pem:/etc/nginx/conf.d/ec_key.pem
      - ./cert.pem:/etc/nginx/conf.d/cert.pem
      - ./index.html:/usr/share/nginx/html/index.html
